# Docker Compose configuration for FaceValue

services:
  web:
    build: .
    entrypoint: ["/app/entrypoint.sh"]
    command: ["gunicorn", "facevalue.wsgi:application", "--bind", "0.0.0.0:8000"]
    ports:
      - "80:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-facevalue.settings}
      - PYTHONPATH=${PYTHONPATH:-/app}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-*}
      - POSTGRES_HOST=${POSTGRES_HOST:-localhost}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-django-insecure-change-this-in-production}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
      - POSTGRES_DB=${POSTGRES_DB:-facevalue}
      - DEBUG=${DEBUG:-False}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/healthz/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
