# Generated by Django 5.2.1 on 2025-05-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facevalue', '0004_alter_slug_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
